### ISSUE TITLE
Quartus ip core compatibility

### ISSUE THREAD

**Issue by Nic30** [Nic30/hwt#7]

**Comment by Nic30** [comment]
@arakan94 can you please provide example quartus IP tcl?

**Comment by arakan94** [comment]
Generated (and mildly modified by hand) by Qsys:
 
[tcl_example.zip](https://github.com/Nic30/HWToolkit/files/1713394/tcl_example.zip)

**Comment by Nic30** [comment]
@arakan94 thank you, after I complete #8 I will implement this feature. (+- 18.2)
